# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Integration_Build
    displayName: Integration Build
    jobs:
      - job:
        steps:
          - task: gitversion/setup@0
            inputs:
              versionSpec: 5.x
          - task: gitversion/execute@0
          - task: NodeTool@0
            inputs:
              versionSpec: 14.x
          - task: Npm@1
            inputs:
              command: custom
              customCommand: run build

  - ${{ if startsWith(variables[ 'Build.SourceBranch' ], 'refs/tags/v') }}:
    - stage: Publish_Tagged_Extension
      displayName: Publish Tagged Extension
      dependsOn: Integration_Build
      jobs:
        - job:
          steps:
            - task: gitversion/setup@0
              inputs:
                versionSpec: '5.x'
            - task: gitversion/execute@0
            - task: NodeTool@0
              inputs:
                versionSpec: '14.x'
            - task: Npm@1
              inputs:
                command: 'custom'
                customCommand: 'run build'
            - task: TfxInstaller@3
              inputs:
                version: 'v0.9.x'
            - task: PublishAzureDevOpsExtension@3
              condition: and(succeeded(), not(contains(variables['GitVersion.SemVer'], '-')))
              inputs:
                connectTo: 'VsTeam'
                connectedServiceName: 'vsts-marketplace'
                fileType: 'vsix'
                vsixFile: 'duchessa-pipelines4s*.vsix'